# Generated by Django 5.0.3 on 2026-04-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_tenant_system'),
        ('inquiries', '0007_update_statuses'),
        ('quotations', '0003_quotation_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inquiry',
            field=models.ForeignKey(blank=True, db_column='inquiry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inquiries.inquiry'),
        ),
        migrations.AddField(
            model_name='event',
            name='quotation',
            field=models.OneToOneField(blank=True, db_column='quotation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='quotations.quotation'),
        ),
    ]
