# Generated by Django 5.0.3 on 2026-04-28 11:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_execution_fields_eventlog'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventlog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='event_logs_event_i_dedc56_idx',
            old_name='event_logs_event_i_9ed267_idx',
        ),
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='event_logs_action__f2e40f_idx',
            old_name='event_logs_action__476d94_idx',
        ),
    ]
