# Generated by Django 5.0.3 on 2026-04-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_inquiry_converted_at_inquiry_converted_event_and_more'),
        ('quotations', '0003_quotation_quote_number'),
        ('tenants', '0001_add_tenant_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('tenant', 'quote_number')},
        ),
        migrations.AddField(
            model_name='quotation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inquiry',
            field=models.ForeignKey(blank=True, db_column='inquiry_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='inquiries.inquiry'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quoted_by',
            field=models.ForeignKey(blank=True, db_column='quoted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='event',
        ),
    ]
