# Generated by Django 5.0.3 on 2026-04-25 13:15

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_planning_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('classic', 'Classic'), ('premium', 'Premium')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('brand_color', models.CharField(default='#2C2C2A', max_length=7)),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('company_bio', models.TextField(blank=True, default='')),
                ('footer_text', models.CharField(blank=True, default='', max_length=255)),
                ('layout_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelManagers(
            name='quotation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotations/pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.quotationtemplate'),
        ),
    ]
