# Generated by Django 5.0.3 on 2026-04-28 11:18

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_replace_quotation_template_with_tenant_snapshot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quotationtemplate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
