# Generated by Django 5.0.3 on 2026-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_quotationtemplate_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='font_family',
            field=models.CharField(blank=True, default='Georgia', max_length=80),
        ),
    ]
