# Generated by Django 5.0.3 on 2026-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_quotation_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='about_text',
            field=models.TextField(blank=True, help_text='Company description shown in About section (Premium only)'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='gallery_images',
            field=models.JSONField(default=list, help_text='List of image URLs for gallery section (Premium only)'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='tier',
            field=models.CharField(choices=[('classic', 'Classic — 2 pages, minimal'), ('standard', 'Standard — 3-4 pages, structured'), ('premium', 'Premium — 6-8 pages, full detail')], default='standard', max_length=20),
        ),
    ]
