# Generated by Django 5.0.3 on 2026-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_quotationtemplate_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='E.g. 50% advance, balance after event'),
        ),
    ]
