# Generated by Django 5.0.3 on 2026-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_quotationtemplate_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='cover_elements',
            field=models.JSONField(default=list, help_text='Drag-drop cover page elements config'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='since_year',
            field=models.CharField(blank=True, default='2013', max_length=4),
        ),
    ]
