# Generated by Django 5.0.3 on 2026-04-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_quotationtemplate_cover_elements_since_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationtemplate',
            name='tier',
        ),
    ]
