# Generated by Django 5.0.3 on 2026-05-18 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0029_gallery_cover_blank'),
        ('tenants', '0005_tenant_default_quotation_template_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationtemplate',
            options={'ordering': ['tenant_id', 'name'], 'verbose_name': 'Quotation template', 'verbose_name_plural': 'Quotation templates'},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='costing_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='grocery_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf_file',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pricing_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.quotationtemplate'),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='configured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_quote_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='font_family',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='pricing_style',
            field=models.CharField(default='simple_total', max_length=20),
        ),
        migrations.CreateModel(
            name='BrandingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='branding/logos/%Y/%m/')),
                ('primary_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('terms_text', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='branding_profiles', to='tenants.tenant')),
            ],
        ),
    ]
