# Generated by Django 5.0.3 on 2026-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_add_follow_up_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
