# Generated by Django 5.0.3 on 2026-04-13 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_inquiry_event_quotation'),
        ('inquiries', '0007_update_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='converted_event',
            field=models.ForeignKey(blank=True, db_column='converted_event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiries', to='events.event'),
        ),
        migrations.CreateModel(
            name='PreEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('guest_count', models.PositiveIntegerField()),
                ('target_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_quote', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('inquiry', models.ForeignKey(db_column='inquiry_id', on_delete=django.db.models.deletion.CASCADE, related_name='pre_estimates', to='inquiries.inquiry')),
            ],
            options={
                'db_table': 'pre_estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreEstimateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pre_estimate', models.ForeignKey(db_column='pre_estimate_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inquiries.preestimate')),
            ],
            options={
                'db_table': 'pre_estimate_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreEstimateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inquiries.preestimatecategory')),
            ],
            options={
                'db_table': 'pre_estimate_items',
                'ordering': ['created_at'],
            },
        ),
    ]
