# Generated by Django 5.0.3 on 2026-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_add_tenant_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
