# Generated by Django 5.0.3 on 2026-04-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_quotationtemplate_alter_quotation_managers_and_more'),
        ('tenants', '0002_tenant_subscription_status_tenant_trial_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='quotations.quotationtemplate'),
        ),
    ]
