# Generated by Django 5.0.3 on 2026-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_dish_name_partial_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('GROCERY', 'Grocery'), ('DISPOSABLE', 'Disposable'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('RENTAL', 'Rental'), ('CHICKEN', 'Chicken'), ('BEEF', 'Beef'), ('MUTTON', 'Mutton'), ('FISH', 'Fish'), ('MEAT', 'Meat'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
