# Generated by Django 5.0.3 on 2026-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_alter_category_managers_alter_dish_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('dozen', 'Dozen'), ('peeled', 'Peeled')], max_length=10),
        ),
    ]
